POST http://localhost:3333/professionals
Content-Type: application/json

{
  "name": "Fagner Barbearia",
  "email": "fagner@barbearia1.com",
  "password": "123"
}

###

GET http://localhost:3333/professionals

###

# Testando a Atualização (PUT)
PUT http://localhost:3333/professionals/0d309c90-0be4-43d2-aa8c-115ff95c2c28
Content-Type: application/json

{
  "name": "Administrador (Editado)",
  "email": "admin.editado@barbearia.com",
  "role": "OWNER"
}

###

# Testando a Inativação (DELETE)
DELETE http://localhost:3333/professionals/c7c9a757-a2ce-47b9-bccb-90821ed32ce8

###

# Testando o Login
POST http://localhost:3333/login
Content-Type: application/json

{
  "email": "fagner@barbearia1.com",
  "password": "123"
}

###

# Testando Cadastro de Cliente (Com senha)
POST http://localhost:3333/customers
Content-Type: application/json

{
  "name": "Carlos Silva",
  "phone": "11999999999",
  "email": "carlos@gmail.com",
  "password": "carlos123"
}

###

# Testando Login do Cliente
POST http://localhost:3333/customers/login
Content-Type: application/json

{
  "email": "carlos@gmail.com",
  "password": "carlos123"
}